version: "3.7"

services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile

    networks:
      - python-x-docker

    depends_on:
      - log_server

  log_server:
    build:
      context: ./
      dockerfile: Dockerfile-logger

    networks:
      - python-x-docker

    expose:
      - "5237/udp"

networks:
  python-x-docker:
